name: Enterprise CI/CD Pipeline


on:

  push:

    branches:
      - develop
      - staging
      - main



jobs:


  build-and-test:

    runs-on: ubuntu-latest


    environment:

      name: ${{ 
        github.ref_name == 'develop' && 'Development' ||
        github.ref_name == 'staging' && 'Staging' ||
        'Production'
      }}


    steps:


    - name: Checkout Code

      uses: actions/checkout@v4



    - name: Setup Node.js

      uses: actions/setup-node@v4

      with:

        node-version: 20



    - name: Install Dependencies

      working-directory: ./app

      run: npm install



    - name: Build Docker Image

      run: docker build -t enterprise-app ./app



    - name: Display Environment

      run: |

        echo "Environment:"
        echo ${{ vars.APP_ENV }}